apiVersion: v1
kind: Service
metadata:
  name: monolit-elasticsearch-service
spec:
  type: NodePort
  selector:
    app: monolit-elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30003