version: "3"
 
services:
    apache:
        build: ./docker/apache
        volumes:
            - ./html:/var/www/html/:z
            - ./docker/apache/php.ini:/usr/local/etc/php/php.ini:z
        ports:
             - "8081:80"
        networks:
            - backend
networks:
    front:
        external:
            name: front
    backend: