apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mysql
spec:
  selector:
    matchLabels:
      app: orders-mysql8
  template:
    metadata:
      labels:
        app: orders-mysql8
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - image: mysql:8
          imagePullPolicy: Always
          name: orders-mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: .orders.
          - name: MYSQL_DATABASE
            value: products
          - name: MYSQL_USER
            value: db_products
          - name: MYSQL_PASSWORD
            value: .prods
          args: ["--skip-name-resolve"]
          ports:
          - containerPort: 3306
          name: orders-mysql8
          volumeMounts:
          - name: dbvol
            mountPath: /var/lib/mysql
      volumes:
        - name: dbvol
          hostPath:
            path: /data/micro_orders/db/