apiVersion: v1
kind: Service
metadata:
  name: orders-mysql8-service
  labels:
    app: orders-mysql8
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    nodePort: 30301
  selector:
    app: orders-mysql8