apiVersion: v1
kind: Service
metadata:
  name: products-web-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8081
    nodePort: 30301
  selector:
    name: products-web-app